# Generated by Django 3.1.7 on 2021-04-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('ifse', models.CharField(max_length=30)),
                ('noOfCustomers', models.IntegerField()),
                ('turnOver', models.IntegerField()),
            ],
        ),
    ]
