# Generated by Django 3.0 on 2021-03-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('num', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('ph', models.IntegerField()),
            ],
        ),
    ]
