# Generated by Django 3.0 on 2021-03-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('eexp', models.IntegerField()),
                ('esal', models.IntegerField()),
                ('eaddr', models.CharField(max_length=100)),
                ('eph', models.IntegerField()),
            ],
        ),
    ]
