# Generated by Django 3.0 on 2021-03-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='num',
            field=models.IntegerField(),
        ),
    ]
